# Generated by Django 4.1.5 on 2023-02-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideline',
            name='version',
            field=models.CharField(default='0.0', max_length=250),
        ),
    ]
